spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:system/oracle@${DB_HOST}:${DB_PORT}:${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none